version: "3.5"
services:
  frontend:
    build: .
    #tty: true
    command: tail -f /dev/null 
    networks:
      - CustomNetwork
  backend:
    build: .
    command: tail -f /dev/null
    networks:
      - CustomNetwork




networks:
  CustomNetwork:
    driver: bridge
